# Day 1 NumPy Notebook

Practice notebook for Day 1 NumPy concepts, organized into small revision sections.


In [1]:
import numpy as np

## Part 1: Python List vs NumPy Array

A Python list repeats values with `* 2`, while a NumPy array multiplies each element.


In [2]:
my_list = [1, 2, 3, 4] * 2
array = np.array([1, 2, 3, 4]) * 2

print(my_list)
print(array)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


## Part 2: Shape, `ndim`, and 3D Indexing

Practice `shape`, `ndim`, and selecting values from a 3D array.


In [3]:
array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'Q'], ['V', 'U', 'W'], ['X', 'Y', 'Z']],
])

picked_letters = array[0, 1, 2] + array[0, 2, 2] + array[2, 1, 2]

print(array.shape)
print(array.ndim)
print(picked_letters)

(3, 3, 3)
3
FIW


## Part 3: 2D Slicing

Practice row slicing, column slicing, and extracting submatrices.


In [4]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
])

print(array.shape)
print(array[0:4:2])
print(array[::-2])
print(array[:, 0:4])
print(array[:, 2:])
print(array[0:2, 0:2])
print(array[2:4, 1:3])

(4, 4)
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 5  6  7  8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[1 2]
 [5 6]]
[[10 11]
 [14 15]]


## Part 4: Dtype and Memory

`dtype` shows the data type and `nbytes` shows total memory usage.


In [5]:
array = np.array([1, 2, 3, 4], dtype=np.int16)

print(array)
print(array.dtype)
print(f'this using {array.nbytes} bytes')

[1 2 3 4]
int16
this using 8 bytes


## Part 5: Exercises 1 to 3


In [6]:
# Exercise 1
array = np.array([10, 20, 30, 40, 50])
print(array[0])
print(array[-1])
print(len(array))

# Exercise 2
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1.shape)
print(array1[1, 1])

# Exercise 3
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array2[:3])
print(array2[-3:])
print(array2[::2])

10
50
5
(3, 3)
5
[1 2 3]
[6 7 8]
[1 3 5 7]


## Part 6: Exercises 4 to 6


In [7]:
# Exercise 4
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array3[0])
print(array3[:, -1])
print(array3[0:2, 0:2])

# Exercise 5
array4 = np.array([1, 2, 3, 4, 5])
print(array4[::-1])

# Exercise 6
array5 = np.array([5, 10, 15, 20])
print(np.sum(array5))
print(np.mean(array5))

[1 2 3]
[3 6 9]
[[1 2]
 [4 5]]
[5 4 3 2 1]
50
12.5


## Part 7: Exercises 7 to 8

Remember: `axis=0` means column-wise and `axis=1` means row-wise.


In [8]:
# Exercise 7
array6 = np.array([[1, 2, 3], [4, 5, 6]])
print(array6.sum(axis=1))
print(array6.sum(axis=0))

# Exercise 8
array7 = np.array([1, 2, 3, 4])
print(array7 + 10)
print(array7 * 2)

[ 6 15]
[5 7 9]
[11 12 13 14]
[2 4 6 8]


## Part 8: Exercises 9 to 10


In [9]:
# Exercise 9
array8 = np.array([10, 15, 20, 25, 30])
print(array8[array8 > 20])

# Exercise 10
rng = np.random.default_rng(42)
random_array = rng.integers(low=1, high=20, size=(4, 4))
print(random_array)
print(np.max(random_array))
print(np.min(random_array))
print(np.mean(random_array))
print(random_array.T)

reversed_row_array = random_array.copy()
reversed_row_array[0] = reversed_row_array[0, ::-1]
print(reversed_row_array)

[25 30]
[[ 2 15 13  9]
 [ 9 17  2 14]
 [ 4  2 11 19]
 [14 15 14 15]]
19
2
10.9375
[[ 2  9  4 14]
 [15 17  2 15]
 [13  2 11 14]
 [ 9 14 19 15]]
[[ 9 13 15  2]
 [ 9 17  2 14]
 [ 4  2 11 19]
 [14 15 14 15]]
