# Day 2 NumPy Notebook

Practice notebook for Day 2 NumPy topics: loop vs vectorized timing, broadcasting, dot product, and Titanic data analysis with NumPy.


In [1]:
import csv
from pathlib import Path

import numpy as np

## Part 1: Loop vs Vectorized Speed Compare

Compare the speed of a Python loop and a NumPy vectorized operation for the same task.


In [2]:
arr = np.arange(1_000_000)

%timeit result = [x * 2 for x in arr]
%timeit arr * 2

63.2 ms ± 2.1 ms per loop (mean ± std. dev. of 5 runs, 1 loop each)
1.36 ms ± 48 us per loop (mean ± std. dev. of 5 runs, 100 loops each)


## Part 2: Broadcasting Example 1

Broadcasting with shape `(3,)` and shape `(3, 1)`.


In [3]:
array1 = np.array([1, 2, 3])
array2 = np.array([[10], [20], [30]])

print(array1, array1.shape)
print(array2, array2.shape)
print(array1 + array2)

[1 2 3] (3,)
[[10]
 [20]
 [30]] (3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


## Part 3: Broadcasting Example 2

Broadcasting with shape `(3, 1)` and shape `(4,)`.


In [4]:
array1 = np.array([[1], [2], [3]])
array2 = np.array([100, 200, 300, 400])

print(array1, array1.shape)
print(array2, array2.shape)
print(array1 + array2)

[[1]
 [2]
 [3]] (3, 1)
[100 200 300 400] (4,)
[[101 201 301 401]
 [102 202 302 402]
 [103 203 303 403]]


## Part 4: Broadcasting Example 3

Broadcasting a 2D array with a 1D scaling array.


In [5]:
image = np.array([[50, 100, 150], [60, 110, 160]])
scale = np.array([1.0, 0.5, 0.2])

print(image, image.shape)
print(scale, scale.shape)
print(image * scale)

[[ 50 100 150]
 [ 60 110 160]] (2, 3)
[1.  0.5 0.2] (3,)
[[50. 50. 30.]
 [60. 55. 32.]]


## Part 5: Dot Product

First compute the dot product manually, then compare it with `np.dot()`.


In [6]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

manual_dot = np.sum(array1 * array2)
numpy_dot = np.dot(array1, array2)

print(manual_dot)
print(numpy_dot)

32
32


## Part 6: Titanic Data Load

Load the Titanic CSV file and convert selected columns into NumPy arrays.


In [7]:
possible_paths = [
    Path('..') / '..' / 'week05-Dataloader_class' / 'titanic.csv',
    Path('week05-Dataloader_class') / 'titanic.csv',
]

for path in possible_paths:
    if path.exists():
        csv_path = path
        break

rows = list(csv.DictReader(open(csv_path, encoding='utf-8')))

survived = np.array([int(row['Survived']) for row in rows])
sex = np.array([row['Sex'] for row in rows])
embarked = np.array([row['Embarked'] if row['Embarked'] else 'Missing' for row in rows])
fare = np.array([float(row['Fare']) for row in rows])
age = np.array([float(row['Age']) if row['Age'] else np.nan for row in rows])

print(len(rows))
print(list(rows[0].keys()))

891
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


## Part 7: `np.where()` on Titanic Data

Use `np.where()` to label fares as `High Fare` or `Regular Fare`.


In [8]:
fare_labels = np.where(fare > 50, 'High Fare', 'Regular Fare')
print(fare_labels[:5])

['Regular Fare' 'High Fare' 'Regular Fare' 'High Fare' 'Regular Fare']


## Part 8: `np.argmax()` on Titanic Data

Use `np.argmax()` to find the index of the oldest passenger.


In [9]:
oldest_index = np.nanargmax(age)

print(oldest_index)
print(rows[oldest_index]['Name'])
print(age[oldest_index])

630
Barkworth, Mr. Algernon Henry Wilson
80.0


## Part 9: `np.unique()` on Titanic Data

Check unique values in the `Sex` and `Embarked` columns.


In [10]:
print(np.unique(sex))
print(np.unique(embarked))

['female' 'male']
['C' 'Missing' 'Q' 'S']
