# Day 3 NumPy Linear Algebra

---

### Multiplying a (32x10) matrix by a (10x5) weight matrix

In [1]:
import numpy as np
from numpy.linalg import *

#### Generating (32x10) matrix and (10x5) by numpy random

In [2]:
rng = np.random.default_rng()

In [3]:
array1 = rng.integers(1,10, size=(32,10))

In [4]:
array2 = rng.integers(1,10,size=(10,5))

In [5]:
print(array1)

[[9 8 6 8 6 1 7 4 7 3]
 [2 3 7 6 9 2 6 2 5 8]
 [6 3 2 9 5 6 7 6 3 8]
 [5 5 8 2 6 2 8 1 9 9]
 [7 8 7 8 3 8 3 1 9 6]
 [4 4 1 2 9 1 8 4 6 5]
 [7 8 2 7 2 6 4 2 2 6]
 [8 9 9 9 9 5 2 3 1 8]
 [6 9 1 5 4 6 3 5 1 1]
 [2 9 3 8 8 2 5 4 1 8]
 [7 7 7 4 5 5 1 2 3 4]
 [7 5 9 9 7 5 4 1 6 3]
 [6 1 5 1 8 4 1 1 1 3]
 [4 3 7 8 4 8 9 9 7 7]
 [7 4 1 4 1 4 6 9 8 8]
 [1 1 2 6 7 9 2 8 4 9]
 [3 1 2 2 3 1 8 7 7 1]
 [9 7 6 7 8 9 8 6 7 6]
 [5 9 8 9 2 7 9 4 4 3]
 [7 3 3 7 6 7 4 1 7 2]
 [7 7 7 4 8 1 4 6 2 9]
 [9 6 1 2 3 6 5 8 9 4]
 [1 9 8 4 7 1 8 2 7 3]
 [6 5 9 1 1 3 8 6 2 9]
 [1 3 5 6 4 8 2 1 5 1]
 [6 7 3 7 5 5 5 2 2 9]
 [2 7 9 6 1 9 1 6 4 6]
 [6 7 7 9 9 6 5 1 3 3]
 [1 3 7 4 7 4 1 6 4 6]
 [9 7 1 4 3 1 1 9 6 7]
 [9 1 4 1 5 3 3 6 7 7]
 [5 9 1 9 5 2 1 6 9 9]]


In [6]:
print(array2)

[[7 6 5 1 6]
 [6 4 1 3 1]
 [5 5 8 2 4]
 [9 8 1 9 1]
 [1 9 3 1 4]
 [8 6 5 4 4]
 [9 6 6 1 4]
 [3 8 3 5 9]
 [7 4 4 7 5]
 [3 4 8 7 8]]


### Using dot and @ and matmul

In [7]:
print(np.dot(array1,array2))  #dot product

[[360 354 238 224 245]
 [265 304 238 203 224]
 [330 345 239 243 261]
 [310 300 283 207 259]
 [382 334 261 265 244]
 [233 272 190 154 212]
 [294 266 188 194 189]
 [343 384 271 243 262]
 [250 255 139 150 164]
 [267 309 195 211 206]
 [255 262 198 163 190]
 [342 340 242 220 219]
 [150 199 153  86 148]
 [399 401 304 287 319]
 [308 300 233 237 283]
 [253 313 218 238 257]
 [211 217 153 134 183]
 [435 442 318 278 329]
 [398 352 254 237 232]
 [301 289 193 191 192]
 [273 331 253 201 269]
 [317 308 222 210 271]
 [288 287 214 179 192]
 [282 276 272 176 262]
 [231 219 149 159 133]
 [299 300 224 213 222]
 [301 290 231 233 227]
 [335 350 228 207 208]
 [208 266 197 184 211]
 [256 282 191 212 256]
 [242 271 229 177 261]
 [313 326 208 285 255]]


In [8]:
print(array1@array2) # using @ for multipication of matrix

[[360 354 238 224 245]
 [265 304 238 203 224]
 [330 345 239 243 261]
 [310 300 283 207 259]
 [382 334 261 265 244]
 [233 272 190 154 212]
 [294 266 188 194 189]
 [343 384 271 243 262]
 [250 255 139 150 164]
 [267 309 195 211 206]
 [255 262 198 163 190]
 [342 340 242 220 219]
 [150 199 153  86 148]
 [399 401 304 287 319]
 [308 300 233 237 283]
 [253 313 218 238 257]
 [211 217 153 134 183]
 [435 442 318 278 329]
 [398 352 254 237 232]
 [301 289 193 191 192]
 [273 331 253 201 269]
 [317 308 222 210 271]
 [288 287 214 179 192]
 [282 276 272 176 262]
 [231 219 149 159 133]
 [299 300 224 213 222]
 [301 290 231 233 227]
 [335 350 228 207 208]
 [208 266 197 184 211]
 [256 282 191 212 256]
 [242 271 229 177 261]
 [313 326 208 285 255]]


In [9]:
print(np.matmul(array1,array2))   #matmul matrix multipication

[[360 354 238 224 245]
 [265 304 238 203 224]
 [330 345 239 243 261]
 [310 300 283 207 259]
 [382 334 261 265 244]
 [233 272 190 154 212]
 [294 266 188 194 189]
 [343 384 271 243 262]
 [250 255 139 150 164]
 [267 309 195 211 206]
 [255 262 198 163 190]
 [342 340 242 220 219]
 [150 199 153  86 148]
 [399 401 304 287 319]
 [308 300 233 237 283]
 [253 313 218 238 257]
 [211 217 153 134 183]
 [435 442 318 278 329]
 [398 352 254 237 232]
 [301 289 193 191 192]
 [273 331 253 201 269]
 [317 308 222 210 271]
 [288 287 214 179 192]
 [282 276 272 176 262]
 [231 219 149 159 133]
 [299 300 224 213 222]
 [301 290 231 233 227]
 [335 350 228 207 208]
 [208 266 197 184 211]
 [256 282 191 212 256]
 [242 271 229 177 261]
 [313 326 208 285 255]]


**(@,dot,matmul) uses for multiplication of matrix and vectors**

## Shape of array/matrix

In [10]:
print("shape of array1:",array1.shape)  #array1 = (32x10),
print("shape of array2:",array2.shape)  #array2 = (10x5) 


shape of array1: (32, 10)
shape of array2: (10, 5)


In [11]:
result = array1 @ array2  # (32,10) @ (10,5) -> inner 10 matches, so output shape becomes (32,5)
print("shape of result:", result.shape)

shape of result: (32, 5)


**rule** - matrix multiplication is valid when the columns of the first matrix match the rows of the second matrix.

## Covariance matrix


In [12]:
hours = [2, 4, 6, 8, 10]
scores = [50, 60, 75, 85, 95]

In [13]:
cov_matrix = np.cov(hours,scores)

In [14]:
print("Covariance Matrix:\n",cov_matrix)

Covariance Matrix:
 [[ 10.   57.5]
 [ 57.5 332.5]]


## Norm types

- `ord=1` -> L1 norm
- `ord=2` -> L2 norm
- `ord=np.inf` -> infinity norm
- `ord='fro'` -> Frobenius norm for matrices


In [15]:
vector = np.array([3,4])
matrix = np.array([[1,2,3],
                   [2,3,4]])

print("Default norm:", np.linalg.norm(vector))
print("L1 norm:", np.linalg.norm(vector, ord=1))
print("L2 norm:", np.linalg.norm(vector, ord=2))
print("Infinity norm:", np.linalg.norm(vector, ord=np.inf))
print("Frobenius norm:", np.linalg.norm(matrix, ord='fro'))

Default norm: 5.0
L1 norm: 7.0
L2 norm: 5.0
Infinity norm: 4.0
Frobenius norm: 6.557438524302


## Mini summary

- Matrix multiplication: `(32,10) @ (10,5) -> (32,5)`
- `@`, `np.dot()`, and `np.matmul()` can all be used for matrix multiplication
- Covariance matrix shows how two variables vary together
- Norms measure vector or matrix size in different ways
